### PR TITLE
Cherry-pick the minor ansible script updates (#201) into ros2 branch

### PR DESCRIPTION
**Pull request by kmiya**
This PR cherry-picks the changes of #201 into ros2 branch.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks fine to me! 👍🏾

**Comment by kmiya** [comment]
@LalithVipulananthan Thanks for reviewing :smiley: 

@UMiho The CI check has failed, but it's no problem. The fail was caused by an unrelated file to this PR.
```
=== src/simulator/scenario_simulator (git) ===
  Could not determine ref type of version: error: cannot run ssh: No such file or directory
  fatal: unable to fork
```

**Comment by kmiya** [comment]
#203 would fix the error on CI.

**Review by UMiho — APPROVED** [review]
@kmiya I got it! LGTM.

**Pull request merged**
