### PR TITLE
Update ROS1->ROS2 porting docs

### PR DESCRIPTION
**Pull request by nnmm**
* Restructuring so that it's less about Fred's and my personal experiences and more of a guide
* Added `GenericTimer` workaround and best practices from https://github.com/tier4/Pilot.Auto/pull/3#issuecomment-706732396
* Added `tf2_ros::Buffer` section

### CODE REVIEW

**Comment by nnmm** [comment]
@simon-t4 Could you please review and merge?

**Review by TakaHoribe — APPROVED** [review]
LGTM except for the `
Semi-automated porting with ros2-migration-tools` part. I haven't tested the ros2-migration-tools, but I'll merge this to share these tips.

**Comment by TakaHoribe** [comment]
@nnmm The document about the installation and timer described here worked in my local. Thank you!

@simon-t4 Please look around this document when you have time.

**Comment by nnmm** [comment]
Yep, Fred got stuck with the semi-automated porting, so I added the "(not working yet)" to the title.

**Pull request merged**
