### PR TITLE
Ade support

### PR DESCRIPTION
**Pull request by esteve**
Add preliminary support for ADE. This enables the use of ADE and Docker to homogenize developer environments.

### CODE REVIEW

**Comment by esteve** [comment]
This is not ready for review yet, but I wanted to push it for visibility.

**Comment by esteve** [comment]
For this to work I'd need access to the "Actions" page so that I can add CI that builds the ADE image and the source code.

**Comment by esteve** [comment]
This is trickier than originally thought, since access to the GitHub Docker registry requires authentication, so it can't be used for uploading Docker images and running the containers (https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358)

I'm adding support for Dockerhub to ADE in https://gitlab.com/ApexAI/ade-cli/-/merge_requests/40 and see if that's a viable alternative, as it does not require authentication for pulling images from public repositories.

**Comment by esteve** [comment]
Support for GitHub in ADE seems it won't be complete:

https://gitlab.com/ApexAI/ade-cli/-/merge_requests/40#note_365582639

instead, I've added support for DockerHub, we can store our images there in the mean time. However, I don't have the password for the autowareci user on DockerHub, so I can't set it up entirely. @mitsudome-r @kfunaoka do you have password for DockerHub? Thanks!

**Comment by mitsudome-r** [comment]
Let's close this since it has been open for long time, and we will move to Autoware.Auto repository after the initial porting is done.

**Pull request closed without merging**
